# Generated by Django 5.1 on 2024-08-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='postal'),
        ),
    ]
