# Generated by Django 5.1 on 2024-08-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_customuser_email_alter_customuser_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='postal',
        ),
    ]
