# Generated by Django 5.1 on 2024-08-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_remove_customuser_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(max_length=10)),
                ('description', models.TextField()),
                ('level', models.TextField()),
                ('image', models.ImageField(upload_to='articles/images/')),
            ],
        ),
    ]
