# Generated by Django 5.1 on 2024-08-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0005_product_productimage_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
