# Generated by Django 5.1 on 2024-08-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0006_product_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
