# Generated by Django 5.1 on 2024-08-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
