# Generated by Django 5.1 on 2024-08-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.TextField(default='without author'),
        ),
    ]
