# Generated by Django 5.1 on 2024-08-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0012_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
